# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test

on:
    push:
        branches: ["master"]
        paths: ["**.ts"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install yarn
              run: npm install -g yarn

            - name: Configure yarn
              run: yarn

            - name: Install backend dependencies
              run: cd backend && yarn install

            - name: Build backend
              run: cd backend && yarn build

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
